// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// diff_file
int diff_file(std::string ofile, std::string nfile, std::string difffile);
RcppExport SEXP _libxdiffR_diff_file(SEXP ofileSEXP, SEXP nfileSEXP, SEXP difffileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type ofile(ofileSEXP);
    Rcpp::traits::input_parameter< std::string >::type nfile(nfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type difffile(difffileSEXP);
    rcpp_result_gen = Rcpp::wrap(diff_file(ofile, nfile, difffile));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_libxdiffR_diff_file", (DL_FUNC) &_libxdiffR_diff_file, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_libxdiffR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
