// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test
int test(std::string ofile, std::string nfile, std::string argv);
RcppExport SEXP _diffutilsR_test(SEXP ofileSEXP, SEXP nfileSEXP, SEXP argvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type ofile(ofileSEXP);
    Rcpp::traits::input_parameter< std::string >::type nfile(nfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type argv(argvSEXP);
    rcpp_result_gen = Rcpp::wrap(test(ofile, nfile, argv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_diffutilsR_test", (DL_FUNC) &_diffutilsR_test, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_diffutilsR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
